### ISSUE TITLE
How to use it if there is no edid.bin exists?

### ISSUE THREAD

**Issue by laichiaheng** [Edenhofer/semt#1]
In the examples, it needs a edid.bin which is already exists, but my monitor doesn't provide me the edid profile.

**Comment by Edenhofer** [comment]
Right, that is the reason why there are some sample edid files provided in the repository. Just use one of those ones and adapt it to your liking using the tool.

**Comment by laichiaheng** [comment]
Thanks, I see it.
I downloaded it from the AUR, so I didn't notice it.
Is it able to add the sound support via HDMI?

**Comment by Edenhofer** [comment]
You are welcome! Btw. a sample file is also provided by the AUR package at `/usr/share/semt/edid.bin.example`.

As of now, the tool is only capable of altering the resolution. I am not even sure how closely related the EDID file is to HDMI sound output.
